# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  example.com:
    site_hosts:
      - portfolio.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: Mario Ernesto - WordPress Theme Developer
    admin_user: admin
    admin_password: admin
    admin_email: admin@example.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://portfolio.dev
      wp_siteurl: http://portfolio.dev/wp
      wp_env: development
      db_name: portfolio_dev
      db_user: portfolio_dbuser
      db_password: portfolio_dbpassword
